# Factor Covariance Modeling

$$\Sigma = F \tilde{\Sigma} F^T + D$$

1. $\Sigma = E(r-\hat{r})(r-\hat{r})^{T}$, as before

2. $F \in R^{n x k}$ is the factor loading matrix with $n$ assets and $k$ factors (i.e. $F_{ij}$ is the loading of asset $i$ onto factor $j$.)

3. $\tilde{\Sigma} \in R^{k x k}$ is the factor covariance matrix, where $\tilde{\Sigma} > 0$. **I'm having trouble with this term**

4. $D \in R^{n x n}$ is a diagonal matrix containing the idiosyncratic risk (i.e., $D_{ii}$ is the variance in asset $i$ not captured by the factors)

This notation is from Stephen Boyd's [short course](http://web.stanford.edu/~boyd/papers/cvx_short_course.html). Specifically slides 13-14 of [this presentation](http://web.stanford.edu/~boyd/papers/pdf/cvx_applications.pdf).

In [16]:
# This is the main method used
from sklearn.decomposition import FactorAnalysis
from sklearn import preprocessing

In [2]:
# Load other methods/packages
import numpy as np
import pandas as pd

In [8]:
# Read data already got from Yahoo! finance
monthly = pd.read_csv('../../../data/monthly.csv', parse_dates = True, index_col = 0)

In [35]:
# Run the factor analysis with k = 10
factor = FactorAnalysis(n_components=50, random_state=101).fit(monthly)

## 1. Covariance Matrix $\Sigma \in R^{n x n}$

In this example $n = 4$ and $k = 3$

In [37]:
Sigma = np.cov(preprocessing.scale(monthly), rowvar = False)
Sigma

array([[ 1.0027027 ,  0.12533049,  0.02409955, ...,  0.0643638 ,
         0.23485312,  0.16056183],
       [ 0.12533049,  1.0027027 ,  0.08696309, ...,  0.11332675,
         0.19865058,  0.20955198],
       [ 0.02409955,  0.08696309,  1.0027027 , ...,  0.07930873,
         0.12047362,  0.23860105],
       ..., 
       [ 0.0643638 ,  0.11332675,  0.07930873, ...,  1.0027027 ,
         0.17749676,  0.14819546],
       [ 0.23485312,  0.19865058,  0.12047362, ...,  0.17749676,
         1.0027027 ,  0.15318908],
       [ 0.16056183,  0.20955198,  0.23860105, ...,  0.14819546,
         0.15318908,  1.0027027 ]])

## 2.  Factor Loading Matrix $F \in R^{n x k}$

In [38]:
# Factor loading matrix (n x k)
F = factor.components_.T
F

array([[ -3.34676272e-02,   1.20728668e-02,  -1.01821718e-02, ...,
         -4.41165807e-03,  -9.43168318e-05,   1.03611546e-02],
       [ -3.60073111e-02,   7.08390572e-03,  -7.18678507e-03, ...,
         -4.35747408e-03,  -6.67790867e-03,  -6.33976162e-03],
       [ -2.46583940e-02,  -1.23974639e-02,  -3.15536530e-03, ...,
         -1.10349981e-03,   7.51859529e-03,  -7.46581505e-03],
       ..., 
       [ -2.57965153e-02,  -1.00942849e-02,   2.23374913e-02, ...,
         -3.46692016e-04,  -5.32318149e-03,   9.84826321e-04],
       [ -6.16632509e-02,   2.01050300e-02,  -1.41952880e-02, ...,
          2.74976925e-03,  -2.14485276e-03,  -5.04773336e-03],
       [ -2.35071254e-02,  -1.74024452e-03,  -2.68517693e-03, ...,
         -3.63271117e-03,   3.18578185e-03,   2.42946098e-03]])

## 3. Factor covariance matrix $\tilde{\Sigma} \in R^{k x k}$?

In [39]:
F @ F.T

array([[ 0.00322369,  0.00164638,  0.00060594, ...,  0.0004041 ,
         0.00280991,  0.00086043],
       [ 0.00164638,  0.0029481 ,  0.00055473, ...,  0.00078077,
         0.0024094 ,  0.00084773],
       [ 0.00060594,  0.00055473,  0.00360714, ...,  0.00054037,
         0.00108989,  0.00102816],
       ..., 
       [ 0.0004041 ,  0.00078077,  0.00054037, ...,  0.00253885,
         0.00131676,  0.00072794],
       [ 0.00280991,  0.0024094 ,  0.00108989, ...,  0.00131676,
         0.01051016,  0.00130359],
       [ 0.00086043,  0.00084773,  0.00102816, ...,  0.00072794,
         0.00130359,  0.00161767]])

## 4. Idiosyncratic Risk  $D \in R^{n x n}$

In [40]:
D = np.diag(factor.noise_variance_)
D

array([[ 0.00820352,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00508516,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00300454, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.00183183,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.00390915,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.00172432]])

## Does it check out?

In [41]:
F @ F.T + D

array([[ 0.01142721,  0.00164638,  0.00060594, ...,  0.0004041 ,
         0.00280991,  0.00086043],
       [ 0.00164638,  0.00803326,  0.00055473, ...,  0.00078077,
         0.0024094 ,  0.00084773],
       [ 0.00060594,  0.00055473,  0.00661168, ...,  0.00054037,
         0.00108989,  0.00102816],
       ..., 
       [ 0.0004041 ,  0.00078077,  0.00054037, ...,  0.00437068,
         0.00131676,  0.00072794],
       [ 0.00280991,  0.0024094 ,  0.00108989, ...,  0.00131676,
         0.01441931,  0.00130359],
       [ 0.00086043,  0.00084773,  0.00102816, ...,  0.00072794,
         0.00130359,  0.00334198]])

In [42]:
factor.get_covariance()

array([[ 0.01142721,  0.00164638,  0.00060594, ...,  0.0004041 ,
         0.00280991,  0.00086043],
       [ 0.00164638,  0.00803326,  0.00055473, ...,  0.00078077,
         0.0024094 ,  0.00084773],
       [ 0.00060594,  0.00055473,  0.00661168, ...,  0.00054037,
         0.00108989,  0.00102816],
       ..., 
       [ 0.0004041 ,  0.00078077,  0.00054037, ...,  0.00437068,
         0.00131676,  0.00072794],
       [ 0.00280991,  0.0024094 ,  0.00108989, ...,  0.00131676,
         0.01441931,  0.00130359],
       [ 0.00086043,  0.00084773,  0.00102816, ...,  0.00072794,
         0.00130359,  0.00334198]])

In [43]:
Sigma

array([[ 1.0027027 ,  0.12533049,  0.02409955, ...,  0.0643638 ,
         0.23485312,  0.16056183],
       [ 0.12533049,  1.0027027 ,  0.08696309, ...,  0.11332675,
         0.19865058,  0.20955198],
       [ 0.02409955,  0.08696309,  1.0027027 , ...,  0.07930873,
         0.12047362,  0.23860105],
       ..., 
       [ 0.0643638 ,  0.11332675,  0.07930873, ...,  1.0027027 ,
         0.17749676,  0.14819546],
       [ 0.23485312,  0.19865058,  0.12047362, ...,  0.17749676,
         1.0027027 ,  0.15318908],
       [ 0.16056183,  0.20955198,  0.23860105, ...,  0.14819546,
         0.15318908,  1.0027027 ]])